---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-oct30-l2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-oct30-l2 
  name: rag-oct30-l2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi